on:
  push:
    branches:
      - main

name: docs

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write # required for PRs, but safer than pushing to main
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: vscode-neovim-fix-word-wrap
          version: "Neovim >= 0.8.0"
          demojify: true
          treesitter: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "auto-generate vimdoc"
          branch: auto/update-vimdoc
          title: "Update vimdoc"
          body: |
            Automated update of vimdoc files.
            This PR was created by the docs workflow.
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
